return {
    Seats = {
        { boneName = 'seat_dside_f',              icon = 'seat', index = -1 },
        { boneName = 'seat_pside_f',              icon = 'seat', index = 0 },
        { boneName = 'seat_dside_r',              icon = 'seat', index = 1 },
        { boneName = 'seat_pside_r',              icon = 'seat', index = 2 },
        { boneName = 'seat_dside_r1',             icon = 'seat', index = 3 },
        { boneName = 'seat_pside_r1',             icon = 'seat', index = 4 },
        { boneName = 'seat_dside_r2',             icon = 'seat', index = 5 },
        { boneName = 'seat_pside_r2',             icon = 'seat', index = 6 },
        { boneName = 'seat_dside_r3',             icon = 'seat', index = 7 },
        { boneName = 'seat_pside_r3',             icon = 'seat', index = 8 },
        { boneName = 'seat_dside_r4',             icon = 'seat', index = 9 },
        { boneName = 'seat_pside_r4',             icon = 'seat', index = 10 },
        { boneName = 'seat_dside_r5',             icon = 'seat', index = 11 },
        { boneName = 'seat_pside_r5',             icon = 'seat', index = 12 },
        { boneName = 'seat_dside_r6',             icon = 'seat', index = 13 },
        { boneName = 'seat_pside_r6',             icon = 'seat', index = 14 },
        { boneName = 'seat_dside_r7',             icon = 'seat', index = 15 },
        { boneName = 'seat_pside_r7',             icon = 'seat', index = 16 },
        { boneName = 'seat_dside_r8',             icon = 'seat', index = 17 },
        { boneName = 'seat_pside_r8',             icon = 'seat', index = 18 },
        { boneName = 'seat_dside_f',              icon = 'seat', index = 19 },
        { boneName = 'seat_pside_r1',             icon = 'seat', index = 20 },
        { boneName = 'seat_dside_r9',             icon = 'seat', index = 21 },
        { boneName = 'seat_pside_r9',             icon = 'seat', index = 22 },
        { boneName = 'seat_dside_r10',            icon = 'seat', index = 23 },
        { boneName = 'seat_pside_r10',            icon = 'seat', index = 24 },
        { boneName = 'seat_dside_r11',            icon = 'seat', index = 25 },
        { boneName = 'seat_pside_r11',            icon = 'seat', index = 26 },
        { boneName = 'seat_dside_r12',            icon = 'seat', index = 27 },
        { boneName = 'seat_pside_r12',            icon = 'seat', index = 28 },
        { boneName = 'seat_dside_r13',            icon = 'seat', index = 29 },
        { boneName = 'seat_pside_r13',            icon = 'seat', index = 30 },
        { boneName = 'seat_dside_r14',            icon = 'seat', index = 31 },
        { boneName = 'seat_pside_r14',            icon = 'seat', index = 32 },
        { boneName = 'seat_dside_r15',            icon = 'seat', index = 33 },
        { boneName = 'seat_pside_r15',            icon = 'seat', index = 34 },
        { boneName = 'seat_dside_r16',            icon = 'seat', index = 35 },
        { boneName = 'seat_pside_r16',            icon = 'seat', index = 36 },
        { boneName = 'seat_dside_r17',            icon = 'seat', index = 37 },
        { boneName = 'seat_pside_r17',            icon = 'seat', index = 38 },
        { boneName = 'seat_dside_r18',            icon = 'seat', index = 39 },
        { boneName = 'seat_pside_r18',            icon = 'seat', index = 40 },
        { boneName = 'seat_dside_r19',            icon = 'seat', index = 41 },
        { boneName = 'seat_pside_r19',            icon = 'seat', index = 42 },
        { boneName = 'seat_dside_r20',            icon = 'seat', index = 43 },
        { boneName = 'seat_pside_r20',            icon = 'seat', index = 44 },
        { boneName = 'seat_dside_r21',            icon = 'seat', index = 45 },
        { boneName = 'seat_pside_r21',            icon = 'seat', index = 46 },
        { boneName = 'seat_dside_r22',            icon = 'seat', index = 47 },
        { boneName = 'seat_pside_r22',            icon = 'seat', index = 48 },
        { boneName = 'seat_dside_r23',            icon = 'seat', index = 49 },
        { boneName = 'seat_pside_r23',            icon = 'seat', index = 50 },
        { boneName = 'seat_dside_r24',            icon = 'seat', index = 51 },
        { boneName = 'seat_pside_r24',            icon = 'seat', index = 52 },
        { boneName = 'seat_dside_r25',            icon = 'seat', index = 53 },
        { boneName = 'seat_pside_r25',            icon = 'seat', index = 54 },
        { boneName = 'seat_dside_r26',            icon = 'seat', index = 55 },
        { boneName = 'seat_pside_r26',            icon = 'seat', index = 56 },
        { boneName = 'seat_dside_r27',            icon = 'seat', index = 57 },
        { boneName = 'seat_pside_r27',            icon = 'seat', index = 58 },
        { boneName = 'seat_dside_r28',            icon = 'seat', index = 59 },
        { boneName = 'seat_pside_r28',            icon = 'seat', index = 60 },
        { boneName = 'seat_dside_r29',            icon = 'seat', index = 61 },
        { boneName = 'seat_pside_r29',            icon = 'seat', index = 62 },
        { boneName = 'seat_dside_r30',            icon = 'seat', index = 63 },
        { boneName = 'seat_pside_r30',            icon = 'seat', index = 64 },
        { boneName = 'LAYOUT_STANDARD',           icon = 'seat', index = 65 },
        { boneName = 'LAYOUT_LOW',                icon = 'seat', index = 66 },
        { boneName = 'LAYOUT_VAN',                icon = 'seat', index = 67 },
        { boneName = 'LAYOUT_VAN_B',              icon = 'seat', index = 68 },
        { boneName = 'LAYOUT_TRUCK',              icon = 'seat', index = 69 },
        { boneName = 'LAYOUT_BIG',                icon = 'seat', index = 70 },
        { boneName = 'LAYOUT_BUS',                icon = 'seat', index = 71 },
        { boneName = 'LAYOUT_BOX_TRUCK',          icon = 'seat', index = 72 },
        { boneName = 'LAYOUT_BOAT',               icon = 'seat', index = 73 },
        { boneName = 'LAYOUT_HELI',               icon = 'seat', index = 74 },
        { boneName = 'LAYOUT_HELI_TRANSPORT',     icon = 'seat', index = 75 },
        { boneName = 'LAYOUT_BIKE',               icon = 'seat', index = 76 },
        { boneName = 'LAYOUT_BICYCLE',            icon = 'seat', index = 77 },
        { boneName = 'LAYOUT_TANK',               icon = 'seat', index = 78 },
        { boneName = 'LAYOUT_PLANE',              icon = 'seat', index = 79 },
        { boneName = 'LAYOUT_QUADBIKE',           icon = 'seat', index = 80 },
        { boneName = 'LAYOUT_AMPHIBIOUS_CAR',     icon = 'seat', index = 81 },
        { boneName = 'LAYOUT_POLICE',             icon = 'seat', index = 82 },
        { boneName = 'LAYOUT_POLICE_BIKE',        icon = 'seat', index = 83 },
        { boneName = 'LAYOUT_AMPHIBIOUS_BIKE',    icon = 'seat', index = 84 },
        { boneName = 'LAYOUT_OPEN_WHEEL_CAR',     icon = 'seat', index = 85 },
        { boneName = 'LAYOUT_UTILITY_TRUCK',      icon = 'seat', index = 86 },
        { boneName = 'LAYOUT_STANDARD_BIKE',      icon = 'seat', index = 87 },
        { boneName = 'LAYOUT_CADDY',              icon = 'seat', index = 88 },
        { boneName = 'LAYOUT_LAWNMOWER',          icon = 'seat', index = 89 },
        { boneName = 'LAYOUT_MOTORCYCLE',         icon = 'seat', index = 90 },
        { boneName = 'LAYOUT_MOTORCYCLE_SPORT',   icon = 'seat', index = 91 },
        { boneName = 'LAYOUT_MOTORCYCLE_CRUISER', icon = 'seat', index = 92 },
        { boneName = 'LAYOUT_COACH',              icon = 'seat', index = 93 },
        { boneName = 'LAYOUT_FIRE_TRUCK',         icon = 'seat', index = 94 },
        { boneName = 'LAYOUT_AMBULANCE',          icon = 'seat', index = 95 },
        { boneName = 'LAYOUT_TAXI',               icon = 'seat', index = 96 },
        { boneName = 'LAYOUT_LIMOUSINE',          icon = 'seat', index = 97 },
        { boneName = 'LAYOUT_RACE_CAR',           icon = 'seat', index = 98 },
        { boneName = 'LAYOUT_MILITARY',           icon = 'seat', index = 99 },
        { boneName = 'LAYOUT_SUBMARINE',          icon = 'seat', index = 100 },
        { boneName = 'LAYOUT_FREIGHT',            icon = 'seat', index = 101 },
        { boneName = 'LAYOUT_BULLDOZER',          icon = 'seat', index = 102 },
        { boneName = 'LAYOUT_GARBAGE_TRUCK',      icon = 'seat', index = 103 },
        { boneName = 'LAYOUT_TOUR_BUS',           icon = 'seat', index = 104 },
        { boneName = 'LAYOUT_STRETCH_LIMO',       icon = 'seat', index = 105 },
        { boneName = 'LAYOUT_LUXURY',             icon = 'seat', index = 106 },
        { boneName = 'LAYOUT_ROCKET_VEHICLE',     icon = 'seat', index = 107 },
        { boneName = 'LAYOUT_HOVERCRAFT',         icon = 'seat', index = 108 },
        { boneName = 'LAYOUT_FUTURISTIC_CAR',     icon = 'seat', index = 109 },
        { boneName = 'LAYOUT_MULTISEAT',          icon = 'seat', index = 110 },
    },
    Doors = {
        {
            boneName = "handle_dside_f",
            icon = 'doorr',
            index = 0,
        },
        {
            boneName = "handle_pside_f",
            icon = 'doorl',
            index = 1,
        },
        {
            boneName = "handle_dside_r",
            icon = 'doorr',
            index = 2,
        },
        {
            boneName = "handle_pside_r",
            icon = 'doorl',
            index = 3,
        },
        {
            boneName = "bonnet",
            icon = 'hood',
            index = 4,
        },
        {
            boneName = "boot",
            icon = 'trunk',
            index = 5,
        },
    },
    Windows = {
        {
            boneName = 'door_dside_f',
            icon = 'windowl',
            index = 0,
        },
        {
            boneName = 'door_pside_f',
            icon = 'windowr',
            index = 1,
        },
        {
            boneName = 'door_dside_r',
            icon = 'windowl',
            index = 2,
        },
        {
            boneName = 'door_pside_r',
            icon = 'windowr',
            index = 3,
        },
    },
    Extras = {
        {
            boneName = 'engine',
            icon = 'engine',
        },
        {
            boneName = 'interiorlight',
            icon = 'interiorlight',
        }
    }
}

-- Vetrox https://discord.gg/jc3bxNTD9Y